- index.html
- src/components/components/ResponsiveCard/ResponsiveCard.module.scss
- src/components/components/ResponsiveCard/ResponsiveCard.module.scss.d.ts
- src/components/components/ResponsiveCard/ResponsiveCard.tsx
- src/components/components/ResponsiveCard/__tests__/ResponsiveCard.test.tsx
- src/components/components/ResponsiveCard/__tests__/__snapshots__/ResponsiveCard.test.tsx.snap
- src/components/stegvisning/AFP/AFP.tsx
- src/components/stegvisning/AFP/__tests__/__snapshots__/AFP.test.tsx.snap
- src/components/stegvisning/OffentligTP/OffentligTP.tsx
- src/components/stegvisning/OffentligTP/__tests__/__snapshots__/OffentligTP.test.tsx.snap
- src/components/stegvisning/Samtykke/Samtykke.tsx
- src/components/stegvisning/Samtykke/__tests__/__snapshots__/Samtykke.test.tsx.snap
- src/components/stegvisning/Sivilstand/Sivilstand.tsx
- src/components/stegvisning/Sivilstand/__tests__/__snapshots__/Sivilstand.test.tsx.snap
- src/components/stegvisning/Start/Start.tsx
- src/components/stegvisning/Start/__tests__/__snapshots__/Start.test.tsx.snap
- retteleser i minimum høyde (gjelder desktop - avstand før footer)
- rettelser i spacing i stegvisning (ResponsiveCard)
> PEK-67 - korrektur

- index.html
> PEK-91: Fjernet glippet mellom applikasjon og dekoratør

- src/components/Simulering/Simulering.tsx
- src/components/TabellVisning/TabellVisning.tsx
- src/components/TabellVisning/__tests__/TabellVisning.test.tsx
- src/components/TabellVisning/__tests__/__snapshots__/TabellVisning.test.tsx.snap
korrigerer visning av tabell når afp eller pensjonsavtaler ikke skal være med
> bugfix tabellvisning

- src/components/common/PageFramework/PageFramework.module.scss
- src/pages/LandingPage/LandingPage.module.scss
- src/pages/LandingPage/LandingPage.tsx
- src/pages/LandingPage/__tests__/__snapshots__/LandingPage.test.tsx.snap
- src/scss/modules/frame.module.scss
- src/scss/modules/frame.module.scss.d.ts
> PEK-60: Oppdater styling

- src/components/Grunnlag/GrunnlagPensjonsavtaler/GrunnlagPensjonsavtaler.tsx
- src/router/routes.tsx
- src/translations/nb.ts
- src/utils/__tests__/test-translations.ts
- src/utils/__tests__/translations.test.tsx
- src/utils/translations.tsx
- legger til href for å få opp cursor pointer
- retter opp lenke mot pensjonsbeholdning (ikke din pensjon)
> bugfiks lenker i grunnlag

- src/components/stegvisning/AFP/__tests__/__snapshots__/AFP.test.tsx.snap
- src/components/stegvisning/Start/Start.tsx
- src/components/stegvisning/Start/__tests__/__snapshots__/Start.test.tsx.snap
- src/utils/translations.tsx
- legger til external ikon på startsiden (personopplysninger)
- styling inline på lenker som vises i tekstavsnitt
> legger til external ikon og inline på lenker

- src/pages/Beregning/Beregning.tsx
- src/pages/Beregning/__tests__/Beregning.test.tsx
- src/state/api/apiSlice.types.ts
- legger til simuleringstype i request body til tidligste-uttaksalder
> simuleringstype til /tidligste-uttaksalder

- .github/workflows/check-pull-request.yaml
- package-lock.json
- package.json
- src/components/Grunnlag/GrunnlagPensjonsavtaler/GrunnlagPensjonsavtaler.tsx
- src/components/Grunnlag/GrunnlagPensjonsavtaler/__tests__/GrunnlagPensjonsavtaler.test.tsx
- src/pages/LandingPage/__tests__/__snapshots__/LandingPage.test.tsx.snap
- src/router/RouteErrorBoundary/__tests__/__snapshots__/ErrorPage404.test.tsx.snap
- src/state/api/__tests__/apiSlice.test.ts
- oppdaterer pakker
- legger til swallowError på apiSlice test
> pakkeoppdatering

- src/components/stegvisning/Start/Start.module.scss
- src/components/stegvisning/Start/Start.tsx
- src/components/stegvisning/Start/__tests__/__snapshots__/Start.test.tsx.snap
- legger til riktig target på personvern lenke
- retter opp styling avvik på kappene
> retter avvikene på start steget

- src/components/Grunnlag/GrunnlagPensjonsavtaler/GrunnlagPensjonsavtaler.module.scss
- src/components/Simulering/Simulering.tsx
- src/pages/Step2/__tests__/Step2.test.tsx
- legger til hand cursor på lenke i pensjonsavtaler feilmeldinger
- øker ved pensjonsavtaler feilmelding for delvis svar
> bugfix styling pensjonsavtaler feilhåndtering

- src/components/Grunnlag/Grunnlag.tsx
- src/components/Grunnlag/__tests__/Grunnlag.test.tsx
- src/state/api/__tests__/typeguards.test.tsx
- src/state/api/typeguards.ts
- fikser bug med 0 inntekt
- tilpasser typeguards til å sjekke mot undefined fram for falsy
> fikser bug med 0 inntekt

- src/components/Simulering/Simulering.tsx
- src/components/Simulering/__tests__/Simulering-utils.test.ts
- src/components/Simulering/utils.ts
utvider processPensjonsberegningArray til å ta høyde for livsvarig pensjon
> Livsvarig alderspensjon / AFP

- src/pages/Beregning/Beregning.tsx
legger til ekstra sjekk på uttaksalder ved visning av melding om for lav opptjening
> feilmelding for lav opptjening

- src/pages/LandingPage/LandingPage.tsx
- src/pages/LandingPage/__tests__/LandingPage.test.tsx
- src/pages/LandingPage/__tests__/__snapshots__/LandingPage.test.tsx.snap
- src/router/RouteErrorBoundary/__tests__/ErrorPageUnexpected.test.tsx
- src/router/routes.tsx
- src/translations/nb.ts
- endrer routing på landingpage fra navigate til window.open
- utvider tester på landingpage
> bugfix triggering idporten ved routing fra "/login" til "/start"

- src/components/Grunnlag/GrunnlagPensjonsavtaler/__tests__/GrunnlagPensjonsavtaler-utils.test.ts
- src/components/Simulering/Simulering.tsx
- src/components/Simulering/__tests__/Simulering.test.tsx
- src/components/Simulering/__tests__/__snapshots__/Simulering.test.tsx.snap
- src/mocks/data/pensjonsavtaler/62.json
- src/mocks/data/pensjonsavtaler/63.json
- src/mocks/data/pensjonsavtaler/64.json
- src/mocks/data/pensjonsavtaler/65.json
- src/mocks/data/pensjonsavtaler/66.json
- src/mocks/data/pensjonsavtaler/67.json
- src/mocks/data/pensjonsavtaler/68.json
- src/mocks/data/pensjonsavtaler/69.json
- src/mocks/data/pensjonsavtaler/70.json
- src/mocks/data/pensjonsavtaler/71.json
- src/mocks/data/pensjonsavtaler/72.json
- src/mocks/data/pensjonsavtaler/73.json
- src/mocks/data/pensjonsavtaler/74.json
- src/mocks/data/pensjonsavtaler/75.json
- src/mocks/handlers.ts
- src/state/api/__tests__/apiSlice.test.ts
- src/state/api/apiSlice.ts
- forbedrer mock data for pensjonsavtaler
- fikser bug med uheldig re-render i Simulering
> Bugfix x-axis graf

- src/components/Grunnlag/GrunnlagForbehold/GrunnlagForbehold.tsx
- src/components/Grunnlag/GrunnlagForbehold/__tests__/__snapshots__/GrunnlagForbehold.test.tsx.snap
- src/components/stegvisning/AFP/__tests__/AFP.test.tsx
- src/components/stegvisning/AFP/__tests__/__snapshots__/AFP.test.tsx.snap
- src/components/stegvisning/Start/Start.tsx
- src/components/stegvisning/Start/__tests__/__snapshots__/Start.test.tsx.snap
- src/context/LanguageProvider/__tests__/LanguageProvider-utils.test.ts
- src/pages/Forbehold/__tests__/__snapshots__/Forbehold.test.tsx.snap
- src/pages/LandingPage/LandingPage.tsx
- src/pages/LandingPage/__tests__/__snapshots__/LandingPage.test.tsx.snap
- src/test-setup.ts
- src/translations/nb.ts
- src/utils/translations.tsx
- utvider translation utils
- legger til svg title på externalIcon lenker
- fjerner aria-hidden på externalIcon lenker
> svg title "åpner i en ny fane"

- src/components/Grunnlag/Grunnlag.tsx
- src/components/Grunnlag/GrunnlagPensjonsavtaler/GrunnlagPensjonsavtalerTable.tsx
- src/components/Simulering/utils-highcharts.ts
- src/components/TabellVisning/TabellVisning.tsx
- src/utils/__tests__/currency.test.ts
- src/utils/currency.ts
- renamer formatAsDecimal til formatWithoutDecimal 
- sikrer heltall i beløpene
> sikrer heltall i beløpene

- public/src/nais.js
- src/components/common/Card/Card.module.scss.d.ts
- src/context/LanguageProvider/__tests__/LanguageProvider-utils.test.ts
- src/context/LanguageProvider/__tests__/LanguageProvider.test.tsx
- src/translations/en.ts
- src/translations/nn.ts
- src/utils/translations.tsx
- oppdaterer auto-genererte styling types definitions
- legger til dummy url i nais.js (fjerner faro warning)
- legger til default locale til 'nb' (fjerner console.error)
- oppdaterer tester med tydeligere oversettelse
> opprydning mot diverse warning og errors ved lokal kjøring

- .github/workflows/check-pull-request.yaml
- .github/workflows/deploy.yaml
- README.md
- src/router/__tests__/__snapshots__/loaders.test.tsx.snap
rebuild-node-sass stegene slettes etter merge
> oppgraderer til Node 20 og Npm 10

- cypress/e2e/pensjon/kalkulator/a11y.cy.ts
- cypress/support/e2e.ts
- public/mockServiceWorker.js
- oppdaterer cypress mock url
- oppdaterer msw generert sw fil
> Install update

- src/components/Grunnlag/GrunnlagForbehold/GrunnlagForbehold.module.scss
- src/components/Simulering/__tests__/Simulering.test.tsx
- src/pages/Beregning/Beregning.tsx
- src/pages/Beregning/__tests__/Beregning.test.tsx
- src/router/__tests__/routes.test.tsx
- src/router/routes.tsx
- endrer navn til den nye fanen fra "detaljert" til "avansert"
- justerer luft mellom forbehold-section og tilbake-til-start-section på beregningsside
> Bugfiks PEK-245

- src/components/Simulering/Simulering.tsx
- src/components/Simulering/__tests__/Simulering.test.tsx
- src/mocks/data/unleash-enable-detaljert-fane.json
- src/pages/Beregning/Beregning.module.scss
- src/pages/Beregning/Beregning.tsx
- src/pages/Beregning/BeregningAvansert.tsx
- src/pages/Beregning/BeregningEnkel.module.scss
- src/pages/Beregning/BeregningEnkel.module.scss.d.ts
- src/pages/Beregning/BeregningEnkel.tsx
- src/pages/Beregning/__tests__/Beregning.test.tsx
- src/pages/Beregning/__tests__/BeregningEnkel.test.tsx
- src/pages/Beregning/index.ts
- splitter Beregning komponent i en komponent for hver fane
> PEK-247 (del 1)

- .github/workflows/deploy.yaml
legger til sjekk for å unngå deploy av prodbygg til dev-gcp ved prod-deploy
> Bugfix deploy

- src/components/EndreInntekt/EndreInntekt.tsx
- src/components/Grunnlag/GrunnlagPensjonsavtaler/__tests__/GrunnlagPensjonsavtaler.test.tsx
- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/components/Simulering/__tests__/Simulering.test.tsx
- src/components/VelgUttaksalder/TemporaryAlderVelgerAvansert.tsx
- src/components/VelgUttaksalder/VelgUttaksalder.tsx
- src/components/common/PageFramework/__tests__/PageFramework.test.tsx
- src/pages/Beregning/__tests__/Beregning.test.tsx
- src/pages/Beregning/__tests__/BeregningEnkel.test.tsx
- src/state/__tests__/__snapshots__/store.test.ts.snap
- src/state/__tests__/store.test.ts
- src/state/listeners/__tests__/uttaksalderListener.test.ts
- src/state/listeners/uttaksalderListener.ts
- src/state/userInput/__tests__/selectors.test.ts
- src/state/userInput/__tests__/userInputReducer.test.ts
- src/state/userInput/selectors.ts
- src/state/userInput/userInputReducer.ts
- flytter `formatertUttaksalder` under `CurrentSimulation`
- oppdaterer dispatch actions og selectors
- fikser selected value under `TemporaryAlderVelgerAvansert`
> refactor formatertUttaksalder

- package-lock.json
- package.json
- public/mockServiceWorker.js
- src/components/Grunnlag/GrunnlagInntekt/__tests__/GrunnlagInntekt.test.tsx
- src/components/Grunnlag/GrunnlagPensjonsavtaler/__tests__/GrunnlagPensjonsavtaler.test.tsx
- src/components/Grunnlag/__tests__/Grunnlag.test.tsx
- src/components/Simulering/__tests__/Simulering.test.tsx
- src/components/TabellVisning/__tests__/TabellVisning.test.tsx
- src/components/TabellVisning/__tests__/__snapshots__/TabellVisning.test.tsx.snap
- src/components/stegvisning/AFP/__tests__/AFP.test.tsx
- src/components/stegvisning/AFP/__tests__/__snapshots__/AFP.test.tsx.snap
- src/components/stegvisning/Samtykke/__tests__/__snapshots__/Samtykke.test.tsx.snap
- src/components/stegvisning/Sivilstand/__tests__/__snapshots__/Sivilstand.test.tsx.snap
- src/components/stegvisning/Utenlandsopphold/__tests__/__snapshots__/Utenlandsopphold.test.tsx.snap
- src/pages/Beregning/__tests__/Beregning.test.tsx
- src/pages/Beregning/__tests__/BeregningEnkel.test.tsx
- src/pages/Step5/__tests__/Step5.test.tsx
- src/pages/StepFeil/__tests__/StepFeil.test.tsx
- src/utils/__tests__/translations.test.tsx
- vite.config.ts
- oppgradering av jsdom
- oppgrdaering av aksel
- refaktorering av enkelte tester
> oppgradering og refaktorering 

- .github/workflows/deploy.yaml
- .nais/deploy-sandbox.yml
- .nais/deploy-veiledning-sandbox.yml
- Et nytt miljø som peker på pensjonskalkulator-backend i dev.
- Appen har startet og er tilgjengelig på https://www.ekstern.dev.nav.no/pensjon/kalkulator-sandbox
- Putter sandbox på slutten for å gjøre det synlig til brukeren
- Det mangler inbound regel inne i backend for å få denne til å fungere på fult
> add sandbox miljø

- src/components/EndreInntekt/__tests__/EndreInntekt.test.tsx
- src/components/EndreInntektVsaPensjon/EndreInntektVsaPensjon.tsx
- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning-utils.test.tsx
- src/components/RedigerAvansertBeregning/utils.ts
- src/components/ResultatkortAvansertBeregning/ResultatkortAvansertBeregning.tsx
- src/components/common/AgePicker/AgePicker.tsx
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
- src/utils/__tests__/alder.test.ts
- src/utils/alder.ts
- legger til validering:
- felles utils for validering av alder
- validering av skjema
- refaktor av names i form. Samler strengene i et constant objekt for å unngå skrivefeil.
> legger til validering

- src/components/EndreInntekt/__tests__/EndreInntekt.test.tsx
- src/components/EndreInntektVsaPensjon/EndreInntektVsaPensjon.module.scss
- src/components/EndreInntektVsaPensjon/EndreInntektVsaPensjon.module.scss.d.ts
- src/components/EndreInntektVsaPensjon/EndreInntektVsaPensjon.tsx
- src/components/RedigerAvansertBeregning/ReadMoreOmPensjonsalder/ReadMoreOmPensjonsalder.tsx
- src/components/RedigerAvansertBeregning/ReadMoreOmPensjonsalder/__tests__/ReadMoreOmPensjonsalder.test.tsx
- src/components/RedigerAvansertBeregning/ReadMoreOmPensjonsalder/__tests__/__snapshots__/ReadMoreOmPensjonsalder.test.tsx.snap
- src/components/RedigerAvansertBeregning/ReadMoreOmPensjonsalder/index.ts
- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.module.scss
- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.module.scss.d.ts
- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/components/common/AgePicker/AgePicker.module.scss
- src/components/common/AgePicker/AgePicker.module.scss.d.ts
- src/components/common/AgePicker/AgePicker.tsx
- src/components/common/AgePicker/__tests__/AgePicker.test.tsx
- src/components/common/AgePicker/__tests__/__snapshots__/AgePicker.test.tsx.snap
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
- legger til ReadMore om uttaksalder og uttaksgrad
- legger til logikk for skjule mulighet til å legge til inntekt vsa 100% alderspensjon når uttaksalder ikke er valgt.
> PEK-292 og PEK-278

- public/mockServiceWorker.js
- src/components/EndreInntektVsaPensjon/EndreInntektVsaPensjon.tsx
- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
legger til nullstilling av aarligInntektVsaPensjon når det velges uttaksalder etter sluttAlder
> Validering

- src/components/EndreInntektVsaPensjon/EndreInntektVsaPensjon.module.scss
- src/components/EndreInntektVsaPensjon/EndreInntektVsaPensjon.module.scss.d.ts
- src/components/EndreInntektVsaPensjon/EndreInntektVsaPensjon.tsx
- src/components/EndreInntektVsaPensjon/__tests__/EndreInntektVsaPensjon.test.tsx
- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning-hooks.test.ts
- src/components/RedigerAvansertBeregning/hooks.tsx
- src/translations/nb.ts
- src/utils/__tests__/inntekt.test.ts
- src/utils/inntekt.ts
- endrer flyten til å håndtere konvertering fra string (value fra TextField) til number (validert riktig, og forventet av backend)
- korrigerer validation error feil kobling
- korrigerer design (padding)
> korrektur inntekt

- .github/workflows/deploy.yaml
> remove api-deploy-key

- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/translations/nb.ts
- nullstiller validation error når uttaksgrad endres
- korrektur tekst
> bugfix PEK-270

- src/pages/Beregning/Beregning.tsx
- fjerner local state og bruker `showModal()` og `close()` istedet, for å holde lukking via kryss i sync
- fjerner selvdestructive addeventlistener og legger flagg for når eventet er lagt til for å tillate Modalen til å vises flere ganger på rad.
> endrer logikk for visning av modal

- src/components/Pensjonsavtaler/Pensjonsavtaler.tsx
- src/components/common/ShowMore/ShowMore.styles.css
- src/components/common/ShowMore/ShowMore.tsx
> PEK 261: Legg til ShowMore for Pensjonsavtaler

- src/components/EndreInntekt/EndreInntekt.tsx
- src/components/EndreInntektVsaPensjon/EndreInntektVsaPensjon.tsx
- src/components/RedigerAvansertBeregning/FormButtonRow.tsx
- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/components/ResultatkortAvansertBeregning/ResultatkortAvansertBeregning.tsx
- src/components/TabellVisning/__tests__/__snapshots__/TabellVisning.test.tsx.snap
- src/components/common/ExpansionCard/ExpansionCard.tsx
- src/components/common/ExpansionCard/__tests__/ExpansionCard.test.tsx
- src/components/common/ExpansionCard/index.ts
- src/pages/Beregning/Beregning.tsx
- src/pages/Beregning/BeregningAvansert.tsx
- src/pages/Beregning/BeregningEnkel.tsx
- src/utils/logging.ts
- Toggle Enkel / Avansert
- button klikk: Beregn pensjon / Oppdater pensjon
- button klikk: Endre valg (resultatkort):
- button klikk:  Legg til inntekt (vsa pensjon) / Endre inntekt
- button klikk:  Oppdater inntekt (vsa pensjon)
- button klikk:  Slett inntekt (vsa pensjon)
- button klikk:  Nullstill
- expansion card
- alert vilkåaarIkkeOppfylt
- alert korrektur på feilskriving "teskt" som skapte en alert none
- valg av uttaksalder for 100 % alderspensjon
- valg av uttaksalder for gradert alderspensjon
- valg av uttaksgrad
- valg av inntekt vsa. gradert pensjon (antall sifre)
> legger til Amplitude logging for avansert fane

- src/components/Grunnlag/Grunnlag.tsx
- src/components/Grunnlag/__tests__/Grunnlag.test.tsx
- src/pages/Beregning/Beregning.tsx
- src/pages/Beregning/BeregningAvansert.tsx
- src/pages/Beregning/BeregningEnkel.tsx
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
- src/types/common-types.ts
> PEK-328: Justeringer i Enkel og Avansert visning

- src/components/Grunnlag/GrunnlagInntekt/GrunnlagInntekt.tsx
- src/translations/nb.ts
> PEK-328: Legg til lenke til avansert i Inntekt frem til uttak

- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning.test.tsx
- src/components/RedigerAvansertBeregning/hooks.tsx
- src/components/RedigerAvansertBeregning/utils.ts
- src/components/Simulering/__tests__/Simulering.test.tsx
- src/components/TidligstMuligUttaksalder/TidligstMuligUttaksalder.tsx
- src/utils/__tests__/alder.test.ts
- src/utils/alder.ts
- renaming isUttaksalderOverMinUttaksaar -> isAlderOverMinUttaksaar
- skriver flere tester for RedigerAvansertBeregning
> legger til tester for avansert skjema

- src/components/Simulering/__tests__/Simulering-utils.test.ts
- src/components/Simulering/utils.ts
...dette gjøres på bedkend allerede
> PEK-298: Fjern utregning av gradering i frontend

- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.module.scss
- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning.test.tsx
- src/components/common/Divider/Divider.module.scss
- src/components/common/Divider/Divider.module.scss.d.ts
- src/components/common/Divider/Divider.tsx
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
(!) obs denne PR'en er en merge mellom 2 bransjer
- endrer rekkefølge i AgePicker(s)
- endrer logikken for handleUtaksgrad slik at uttaksalder overføres mellom AgePicker for gradert og helt
- endrer labels
> retter opp rekkefølgen uten TMU

- src/components/RedigerAvansertBeregning/utils.ts
- src/pages/Beregning/BeregningAvansert.tsx
- src/pages/Beregning/BeregningEnkel.tsx
- logging for gjennomføringsgrad
- logging for endring av inntekt vsa 100 % alderspensjon
> legger til amplitude logging

- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning-hooks.test.tsx
- src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning-utils.test.tsx
- src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning.test.tsx
- src/components/RedigerAvansertBeregning/hooks.tsx
- src/components/RedigerAvansertBeregning/utils.ts
- src/components/VelgUttaksalder/VelgUttaksalder.tsx
- src/pages/Beregning/__tests__/BeregningAvansert.test.tsx
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
- fjerner forhåndsfylling av uttaksgrad
- legger til validering
> fjerner forhåndsfylling av uttaksgrad

- .github/workflows/deploy.yaml
- .nais/deploy-catbox.yml
- .nais/deploy-veiledning-catbox.yml
Kunne ikke bestemme hvilken katt for å bli ett miljø 🐈‍⬛
> legg til et catbox miljø

- src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning-hooks.test.tsx
- src/components/RedigerAvansertBeregning/hooks.tsx
- src/components/RedigerAvansertBeregning/utils.ts
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
- justerer valideringstekst
- justerer valideringslogikk for sluttAlder (inntekt vsa. 100 % alderspensjon)
> justerer valideringstekst og logikk i avansert

- src/mocks/data/ekskludert-status.json
- src/mocks/data/unleash-enable-ufoere.json
- src/mocks/handlers.ts
- src/pages/Step0/Step0.tsx
- src/pages/Step0/__tests__/Step0.test.tsx
- src/state/api/__tests__/apiSlice.test.ts
- src/state/api/apiSlice.ts
- legger til feature toggle for uføre
- logikk for å vise henvisning til uføre feilssiden kun når feature togglen er av
> Uføre leveranse 1 - PEK-332

- src/components/stegvisning/OffentligTP/OffentligTP.tsx
- src/components/stegvisning/OffentligTP/__tests__/OffentligTP.test.tsx
- src/components/stegvisning/Start/Start.tsx
- src/components/stegvisning/Start/__tests__/Start.test.tsx
- src/components/stegvisning/Start/__tests__/__snapshots__/Start.test.tsx.snap
- src/pages/Step0/Step0.tsx
- src/pages/Step3/Step3.tsx
- src/router/__tests__/__snapshots__/loaders.test.tsx.snap
- src/router/__tests__/loaders.test.tsx
- src/router/loaders.tsx
- src/router/routes.tsx
- src/types/types.d.ts
- renamer og refaktorerer `useTpoMedlemskapAccessData` til `useStep3AccessData`
- tilpasser logikk og navngivning i Step0
> Mh/pek 400 loaders (del 2) 

- src/pages/Step0/__tests__/Step0.test.tsx
- src/pages/Step4/Step4.tsx
- src/pages/Step4/__tests__/Step4.test.tsx
legger til logikk for ekskludering av ulike grupper på steg 4 i tilfelle kallet feilet tidligere
> Steg 4 - logikk for ekskludering

- src/pages/Forbehold/__tests__/__snapshots__/Forbehold.test.tsx.snap
- src/pages/Personopplysninger/Personopplysninger.tsx
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
- innholdoppdatering forbehold og personopplysninger
> Uføre L6 - innholdoppdatering

- src/mocks/handlers.ts
- src/pages/VeilederInput/VeilederInput.tsx
- src/state/__tests__/__snapshots__/store.test.ts.snap
- src/state/__tests__/store.test.ts
- src/state/api/apiSlice.ts
- src/state/userInput/__tests__/selectors.test.ts
- src/state/userInput/__tests__/userInputReducer.test.ts
- src/state/userInput/selectors.ts
- src/state/userInput/userInputReducer.ts
Ligger i `catbox`: https://pensjonskalkulator-veiledning-frontend-catbox.ansatt.dev.nav.no/pensjon/kalkulator/veileder
> PEK-459: Bruk kryptert fnr for veileder

- src/mocks/handlers.ts
- src/translations/nb.ts
> PEK-501: Oppdater tekst på uinnlogget kalkulator

- src/components/Simulering/__tests__/Simulering-utils.test.ts
- src/components/Simulering/utils.ts
legger til logikk for korrekt beregning av inntekt vsa pensjon innen ett år
> Bugfix PEK-535

- src/components/Simulering/__tests__/Simulering-utils.test.ts
- src/components/Simulering/utils.ts
- src/components/UtenlandsoppholdListe/UtenlandsoppholdListe.module.scss
> Catbox (allerede reviewed)

- src/components/Grunnlag/Grunnlag.tsx
- src/components/Grunnlag/GrunnlagUtenlandsopphold/GrunnlagUtenlandsopphold.tsx
- src/components/Grunnlag/GrunnlagUtenlandsopphold/__tests__/GrunnlagUtenlandsopphold.test.tsx
- src/components/Grunnlag/__tests__/Grunnlag.test.tsx
- src/components/SavnerDuNoe/SavnerDuNoe.tsx
- src/components/TidligstMuligUttaksalder/TidligstMuligUttaksalder.tsx
- src/components/TidligstMuligUttaksalder/__tests__/TidligstMuligUttaksalder.test.tsx
- src/pages/Beregning/Beregning.tsx
- src/pages/Beregning/BeregningAvansert.tsx
- src/pages/Beregning/BeregningEnkel.tsx
- src/pages/Beregning/__tests__/Beregning.test.tsx
- src/state/userInput/__tests__/userInputReducer.test.ts
- src/state/userInput/userInputReducer.ts
- endrer flushCurrentSimulation til flushCurrentSimulationUtenomUtenlandsperioder
- endrer logikk for henting av harForLiteTrygdetid
> Bugfix PEK-542

- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning.test.tsx
- src/pages/Beregning/BeregningAvansert.tsx
- src/pages/Beregning/BeregningEnkel.tsx
- src/pages/Beregning/__tests__/BeregningEnkel.test.tsx
- src/translations/nb.ts
- src/utils/__tests__/alder.test.ts
- src/utils/alder.ts
Avgrense valg i aldersvelger etter brukers alder i enkelt og avansert
> Mh/pek 575 -> catbox

- .github/workflows/deploy.yaml
- .nais/deploy-dreambox.yml
- .nais/deploy-veiledning-dreambox.yml
> Dreambox -> main (allerede reviewed)

- src/components/stegvisning/AFP/AFP.tsx
endrer på state for visning av alert for vet_ikke AFP valg
> Bugfix PEK-518

- cypress/e2e/pensjon/kalkulator/utland.cy.ts
justering på cypress utland tester som er ustabile
> Bugfix PEK-699

- src/router/loaders.tsx
korrigerer logikk for feilhåndtering i AFP-loader
> Bugfix PEK-731

- .docker/Dockerfile
- .github/workflows/check-pull-request.yaml
- .github/workflows/deploy.yaml
- package-lock.json
- package.json
- server/server.ts
- src/router/__tests__/__snapshots__/loaders.test.tsx.snap
- **Fjern ubrukt proxy i server**
- **Bump alle bygg til 22.11.0**
- **Byttet til distroless image for node konteiner**
> PEK-684: Oppdater til Node 22

- cypress/e2e/pensjon/kalkulator/pensjonsavtaler.cy.ts
- cypress/fixtures/offentlig-tp.json
- cypress/support/e2e.ts
- src/components/Pensjonsavtaler/OffentligTjenestepensjon.tsx
- src/components/Pensjonsavtaler/Pensjonsavtaler.tsx
- src/components/Pensjonsavtaler/__tests__/OffentligTjenestepensjon.test.tsx
- src/components/Pensjonsavtaler/__tests__/Pensjonsavtaler.test.tsx
- src/components/Simulering/Simulering.tsx
- src/components/Simulering/__tests__/Simulering-hooks.test.tsx
- src/components/Simulering/__tests__/Simulering.test.tsx
- src/components/Simulering/hooks.tsx
- src/mocks/data/offentlig-tp.json
- src/mocks/data/tpo-medlemskap.json
- src/mocks/handlers.ts
- src/mocks/mockedRTKQueryApiCalls.ts
- src/pages/Beregning/__tests__/BeregningAvansert.test.tsx
- src/pages/Beregning/__tests__/BeregningEnkel.test.tsx
- src/pages/StepSamtykkePensjonsavtaler/StepSamtykkePensjonsavtaler.tsx
- src/pages/StepSamtykkePensjonsavtaler/__tests__/StepSamtykkePensjonsavtaler.test.tsx
- src/state/api/__tests__/apiSlice-utils.test.ts
- src/state/api/__tests__/apiSlice.test.ts
- src/state/api/__tests__/typeguards.test.tsx
- src/state/api/apiSlice.ts
- src/state/api/typeguards.ts
- src/state/api/utils.ts
- src/state/userInput/__tests__/selectors.test.ts
- src/state/userInput/selectors.ts
- src/types/schema.d.ts
- src/types/types.d.ts
> Sandbox -> Main (already reviewed)

- src/components/TabellVisning/TabellVisning.tsx
- src/components/TabellVisning/__tests__/TabellVisning.test.tsx
- src/pages/Beregning/__tests__/BeregningEnkel.test.tsx
legger til sjekk for at inntekt serie er med før den legges som kolonne i tabell
> PEK-858: Bug med inntekt 0 i tabell

- cypress/e2e/pensjon/kalkulator/hovedhistorie.cy.ts
- src/components/stegvisning/SamtykkePensjonsavtaler/SamtykkePensjonsavtaler.tsx
- src/components/stegvisning/SamtykkePensjonsavtaler/__tests__/__snapshots__/SamtykkePensjonsavtaler.test.tsx.snap
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
oppdaterer samtykke steget og forbehold
> PEK-795 + PEK-877

- src/router/constants.ts
- src/translations/nb.ts
Inneholder også PEK-875, men resten av lenkene oppdateres i pselv.
> PEK-872: Lagt til tekst på landingsside

- cypress/e2e/pensjon/kalkulator/med-samtykke-offentlig-tjenestepensjon.cy.ts
- src/components/Pensjonsavtaler/OffentligTjenestePensjon/__tests__/OffentligTjenestepensjon.test.tsx
- src/translations/en.ts
- src/translations/nb.ts
https://jira.adeo.no/browse/PEK-938
> PEK-938: Endre tekst under "Offentlig tjenestepensjon"

- src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
- src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning.test.tsx
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
Blir samme tekst som de som ikke har vedtak om AP.
https://jira.adeo.no/browse/PEK-992
> PEK-992: Endre tekst om uttaksgrad for de med vedtak om AP og full UT

- .github/workflows/deploy-sanity.yaml
- .github/workflows/deploy.yaml
Har testet litt, og funnet ut at det eneste som trengs utover defaulten er `id-token: 'write'`.
> Endre permissions på workflows

- src/mocks/handlers.ts
Rydder opp i feilmeldinger i konsollen.
> Legg til mock i MSW for harRepresentasjonsforhold

- cypress/e2e/pensjon/kalkulator/endring.cy.ts
- cypress/e2e/pensjon/kalkulator/hovedhistorie.cy.ts
- cypress/e2e/pensjon/kalkulator/omstillingsstoenad-og-gjenlevende.cy.ts
- cypress/e2e/pensjon/kalkulator/ufoeretrygd.cy.ts
- cypress/fixtures/loepende-vedtak-endring.json
- cypress/fixtures/loepende-vedtak.json
- cypress/support/e2e.ts
- src/components/AvansertSkjema/AvansertSkjemaForAndreBrukere/__tests__/AvansertSkjemaForAndreBrukere.test.tsx
- src/components/AvansertSkjema/AvansertSkjemaForBrukereMedGradertUfoeretrygd/__tests__/AvansertSkjemaForBrukereMedGradertUfoeretrygd.test.tsx
- src/components/AvansertSkjema/__tests__/AvansertSkjema-utils.test.tsx
- src/components/EndreInntekt/__tests__/EndreInntekt.test.tsx
- src/components/InfoOmFremtidigVedtak/InfoOmFremtidigVedtak.tsx
- src/components/Pensjonsavtaler/__tests__/Pensjonsavtaler.test.tsx
- src/components/Simulering/__tests__/Simulering.test.tsx
- src/components/stegvisning/Start/__tests__/Start.test.tsx
- src/mocks/data/loepende-vedtak.json
- src/mocks/handlers.ts
- src/mocks/mockedRTKQueryApiCalls.ts
- src/pages/StepStart/__tests__/StepStart.test.tsx
- src/router/__tests__/loaders.test.tsx
- src/router/__tests__/routes.test.tsx
- src/router/loaders.tsx
- src/state/api/__tests__/apiSlice-utils.test.ts
- src/state/api/__tests__/apiSlice.test.ts
- src/state/api/__tests__/typeguards.test.tsx
- src/state/api/apiSlice.ts
- src/state/api/typeguards.ts
- src/state/userInput/__tests__/selectors.test.ts
- src/translations/nb.ts
- src/types/types.d.ts
> Migrering til LoependeVedtakV4

- src/state/userInput/selectors.ts
Se beskrivelsen på https://github.com/navikt/pensjonskalkulator-frontend/pull/1809 for bakgrunn.
> Refaktorert selectors

- src/components/common/SanityReadmore/SanityReadmore.module.scss
- src/components/common/SanityReadmore/SanityReadmore.module.scss.d.ts
- src/components/common/SanityReadmore/SanityReadmore.tsx
- src/components/stegvisning/AFP/__tests__/__snapshots__/AFPPrivat.test.tsx.snap
- src/components/stegvisning/SamtykkePensjonsavtaler/__tests__/__snapshots__/SamtykkePensjonsavtaler.test.tsx.snap
- src/components/stegvisning/Ufoere/__tests__/__snapshots__/Ufoere.test.tsx.snap
> Fjern margin-top i SanityReadmore

- .github/copilot-instructions.md
Forslag til ett tekstdokument som github Copilot bruker når vi lager AI generert kode, setter alle på Review så alle kan komme med forslag, eller si ifra om det er ett dårlig forslag :)
> Legg til copilot instruksjoner for å ha mer forutsigbar KI kode

- src/components/AvansertSkjema/AvansertSkjemaForAndreBrukere/AvansertSkjemaForAndreBrukere.tsx
- src/components/AvansertSkjema/AvansertSkjemaForBrukereMedGradertUfoeretrygd/AvansertSkjemaForBrukereMedGradertUfoeretrygd.tsx
- src/components/AvansertSkjema/hooks.tsx
- src/components/AvansertSkjema/utils.ts
- src/state/api/utils.ts
Skru på "Hide whitespace" når du ser på diffen.
> Diverse refaktorering

- cypress/e2e/pensjon/kalkulator/henvisning.cy.ts
- src/pages/Henvisning/Henvisning.tsx
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
- Justere tekster for apotekerne
> PEK-1109: Oppdatere tekster

- cypress/e2e/pensjon/kalkulator/hovedhistorie.cy.ts
- cypress/e2e/pensjon/kalkulator/med-samtykke-offentlig-tjenestepensjon.cy.ts
- cypress/fixtures/toggle-otp-fra-klp.json
- src/mocks/data/unleash-otp-fra-klp.json
https://jira.adeo.no/browse/PEK-1035
> Cypress-tester for KLP

- eslint.config.mjs
- server/server.ts
- **Redirect for G-regulering**
- **Fjern server.js fra eslint, feiler etter oppdatering og flere tsconfig filer**
> G-regulering kill-switch

- src/pages/LandingPage/LandingPage.tsx
- src/pages/LandingPage/__tests__/LandingPage.test.tsx
- src/router/__tests__/routes.test.tsx
- src/translations/en.ts
- src/translations/nb.ts
- src/translations/nn.ts
[PEK-1323](https://jira.adeo.no/projects/PEK/issues/PEK-1323?filter=allopenissues)
> Landingsside endret for kap19 (PEK-1323)

- .github/workflows/backup-sanity-dataset.yaml
- README.md
Skrive README og vise at backup er en ndjson-fil
> PEK-1219 skriv tydelig at backup er ndjson. Oppdater README

- src/components/AvansertSkjema/AvansertSkjemaForBrukereMedKap19Afp/AvansertSkjemaForBrukereMedKap19Afp.tsx
- src/components/Grunnlag/Grunnlag.tsx
- src/components/GrunnlagForbehold/GrunnlagForbehold.tsx
- src/components/TidligstMuligUttaksalder/TidligstMuligUttaksalder.tsx
- src/components/VilkaarsproevingAlert/VilkaarsproevingAlert.tsx
Send tracking på interne lenker og lenker som har ikke sporing fra før via `onClick`.
> PEK 852 log links

- src/pages/VeilederInput/VeilederInput.tsx
- src/state/session/sessionSlice.ts
[PEK-1428](https://jira.adeo.no/projects/PEK/issues/PEK-1428)
> PEK-1428 fix bruker state veileder
