src/pages/Step2/Step2.tsx
src/pages/Step2/__tests__/Step2.test.tsx

Når brukeren velger Nei på samtykke (Steg 2), sørger for at
- responser fra tidligere kall nullstilles 
- feature toggle, person og inntekt fetches på nytt

retter opp bug ved nullstilling av storen på samtykke steg

---

src/components/Simulering/__tests__/__snapshots__/Simulering-utils-highcharts.test.ts.snap
src/components/Simulering/utils-highcharts.ts
src/state/listeners/__tests__/uttaksalderListener.test.ts
src/state/listeners/uttaksalderListener.ts

- fjerner animasjon for søyler i graphen (beholder kun start-animasjonen)
- fjerner fetching av pensjonsavtaler i listener (unødvendig i og med at pensjonsavtaler fetches hver gang valgt uttaksalder endres i Simulering)

fjerner animasjon og fjerner fetching av pensjonsavtaler i listener

---

.github/workflows/deploy.yaml
.nais/deploy-veiledning-dev.yml

Konfig for tilgang som NAV-ansatt veileder (foreløpig bare i _dev_).
Hovedforskjellen mellom "veileder"-versjon og normal versjon er denne NAIS-konfigen:
```
azure:
application:
enabled: true
claims:
groups:
- id: "a3f91493-1ab8-4b64-a544-0a77cbba9240" # 0000-GA-Pensjon_VEILEDER
- id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
- id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
- id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
extra:
- NAVident
sidecar:
enabled: true
```
Her er [Azure AD sidecar](https://doc.nais.io/security/auth/azure-ad/sidecar/) skrudd på, hvilket gjør at uinnloggede brukere vil omdirigeres til Entra ID (Azure AD) for innlogging som NAV-ansatt.
Entra ID vil utstede et token (JWT) som vil inneholde …

PEK-233 Deploy version for veiledere (dev only)

---

src/components/Simulering/Simulering.module.scss
src/components/Simulering/Simulering.module.scss.d.ts
src/components/Simulering/__tests__/__snapshots__/Simulering-utils-highcharts.test.ts.snap
src/components/Simulering/utils-highcharts.ts

- legger til eksplisitt konfigurasjonsparameter `outside` til `false` i highcharts slik at tooltip alltid plasseres inne i scrolling-området
- ordner stacking context (z-index) på de ulike highcharts layers slik at tooltip alltid vises øverst, og svg-søylene nederst. 
- fjerner scrolling-mask på venstre og høyre side (fordi svg-element kan vi ikke kontrollere z-index på), og legger heller en hvit gradert bakgrunn fra y-axis slik.

Bugfix tooltip plassering ved scroll

---

src/pages/Beregning/Beregning.module.scss
src/pages/Beregning/BeregningAvansert.module.scss
src/pages/Beregning/BeregningAvansert.module.scss.d.ts
src/pages/Beregning/BeregningAvansert.tsx
src/pages/Beregning/BeregningEnkel.module.scss
src/pages/Beregning/BeregningEnkel.module.scss.d.ts
src/pages/Beregning/BeregningEnkel.tsx

- setter hvit bakgrunn som default på `Beregning` (istedenfor lysgrå tidligere)
- legger til felt for lysgrå bakgrunn øverst på siden
- fjerner alle de hvite feltene som er nå unødvendig

Forenkler logikken for bakgrunnsfarge på beregningssiden

---

src/components/EndreInntektVsaPensjon/EndreInntektVsaPensjon.tsx
src/components/EndreInntektVsaPensjon/__tests__/EndreInntektVsaPensjon.test.tsx
src/components/Grunnlag/GrunnlagPensjonsavtaler/GrunnlagPensjonsavtaler.tsx
src/components/Grunnlag/GrunnlagPensjonsavtaler/__tests__/GrunnlagPensjonsavtaler.test.tsx
src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
src/components/ResultatkortAvansertBeregning/ResultatkortAvansertBeregning.tsx
src/components/Simulering/Simulering.tsx
src/components/Simulering/__tests__/Simulering.test.tsx
src/mocks/handlers.ts
src/pages/Beregning/BeregningAvansert.tsx
src/pages/Beregning/BeregningEnkel.tsx
src/pages/Beregning/__tests__/Beregning.test.tsx
src/pages/Beregning/__tests__/BeregningEnkel.test.tsx
src/state/__tests__/__snapshots__/store.test.ts.snap
src/state/__tests__/store.test.ts
src/state/api/__tests__/apiSlice-utils.test.ts
src/state/api/__tests__/apiSlice.test.ts
src/state/api/apiSlice.ts
src/state/api/utils.ts
src/state/userInput/__tests__/selectors.test.ts
src/state/userInput/__tests__/userInputReducer.test.ts
src/state/userInput/userInputReducer.ts
src/types/schema.d.ts
src/types/types.d.ts

- tilpasser til simuleringsendepunkt v2 ved og:
-  lage ny funksjon `generateAlderspensjonRequestBody` (i tillegg til `generateAlderspensjonEnkelRequestBody`)
-  legge til siste Swagger types manuelt i schema.d.ts
- utvider types
- legger til gradert uttaksperiode i kall til pensjonsavtaler (oppdaterer `generatePensjonsavtalerRequestBody`)
(!) Obs v1 av simuleringsendepunktet er fortsatt i bruk for enkel simulering

PEK-247 - kobler mot v2 av simuleringsendepunktet

---

src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
src/components/RedigerAvansertBeregning/__tests__/RedigerAvansertBeregning-hooks.test.tsx
src/components/RedigerAvansertBeregning/hooks.tsx
src/mocks/handlers.ts
src/pages/Beregning/Beregning.tsx
src/pages/Beregning/BeregningAvansert.tsx
src/pages/Beregning/BeregningEnkel.tsx
src/pages/Beregning/__tests__/Beregning.test.tsx
src/pages/Beregning/__tests__/BeregningEnkel.test.tsx

- flytter kode relatert til henting av TMU under Enkel fane
Dette med hensikt om å skille logikken for TMU Enkel fra TMU avansert (på grunn av en loop som er skapt ved redirect fra avansert til enkel fane når TMU har feilet)

Refactor TMU Pensjonskalkulator Enkel

---

src/components/Simulering/Simulering.tsx
src/components/Simulering/__tests__/Simulering-utils.test.ts
src/components/Simulering/utils.ts

- fjerner sjekk om at inntekt vsa pensjon er oppgitt (det skal beregnes for alle, uansett)
- tilpasser logikken til undefined sluttAlder
- legger til ny test for å dekke dette tilfellet

bugfix inntekt array

---

.nais/deploy-veiledning-catbox.yml
.nais/deploy-veiledning-prod.yml
.nais/deploy-veiledning-sandbox.yml
.nais/deploy-veiledning-staging.yml

Dette vil gi fortsatt tilgang til veileder-appen uten naisdevice etter 21. mai 2024.
Ref. [Slack-melding](https://nav-it.slack.com/archives/C013XV66XHB/p1714640138094089)

Use 'ansatt' ingress

---

src/components/Pensjonsavtaler/OffentligTjenestePensjon/OffentligTjenestepensjon.tsx

- legger til formatering av lenker i OffentligTjenestepensjon komponent
- korrigerer feil parentese

Bugfix PEK-814

---

.github/workflows/check-pull-request.yaml
.github/workflows/deploy.yaml
eslint.config.mjs
package-lock.json
package.json
scripts/CustomPostCSSLoader.js
vite.config.ts

- Endret til å bruke `sass` i stedet for `node-sass` slik at vi kan bruke siste node-versjon.
- Gjorde slik at det fungerer i Windows.
- Av en eller annen grunn fungerer det ikke med Windows path separator, så la til `replaceAll('\\', '/')`.
- `path.join(this.root, relativeDir)` resulterte i `C:\C:\path-til-fil` i Windows. Så vidt jeg kunne se var denne koden unødvendig da `relativeDir` alltid er en absolutt path, så jeg bare fjernet det.

CustomPostCSSLoader: Migrer fra node-sass til sass + Win-støtte

---

src/context/LanguageProvider/LanguageProvider.tsx
tsconfig.json

Eksempel:
(`"moduleResolution": "bundler"` trengs for å kunne importere fra `@navikt/ds-react/locales`)

Aksel-komponenter respekterer valgt språk

---

cypress.config.ts
cypress/e2e/pensjon/kalkulator/hovedhistorie.cy.ts
cypress/e2e/pensjon/kalkulator/ufoeretrygd.cy.ts

https://jira.adeo.no/secure/Tests.jspa#/testCase/PEK-T10

PEK-776: Cypress: 2 nye steg i ufoeretrygd.cy.ts ifm. mottar uføretrygd og >62 år

---

src/components/common/ShowMore/ShowMore.tsx

Det ser ut til at React 19 nå har fått offisiell støtte for `inert`-attributtet, slik at denne nå må settes til `true` i stedet for tom streng for å virke.

Fiks inert-attributt i ShowMore

---

cypress/e2e/pensjon/kalkulator/ufoeretrygd.cy.ts
src/components/TidligstMuligUttaksalder/__tests__/TidligstMuligUttaksalder.test.tsx
src/components/stegvisning/Ufoere/__tests__/__snapshots__/Ufoere.test.tsx.snap
src/translations/en.ts
src/translations/nb.ts

Justerte teksten `stegvisning.ufoere.ingress` ihht. PEK-904.
Fikset i samme slengen en liten skrivefeil jeg fant i `beregning.read_more.pensjonsalder.body`.

PEK-904: Fjern tekst "i privat sektor"

---

src/components/RedigerAvansertBeregning/RedigerAvansertBeregning.tsx
src/components/UtenlandsoppholdModal/UtenlandsoppholdModal.tsx
src/components/common/AgePicker/AgePicker.tsx

Bruk av `selected` på `<option>` gir følgende feilmelding i nettleser-konsollen:
```
Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
```

Fjern `selected` på `<option>`

---

.husky/pre-commit

Fikk denne meldingen ved kjøring av `git commit`:
```
husky - DEPRECATED
Please remove the following two lines from .husky/pre-commit:
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
They WILL FAIL in v10.0.0
```

Fjernet deprecated linjer i pre-commit

---

sanity.cli.ts
sanity.config.ts
src/context/LanguageProvider/LanguageProvider.tsx
src/context/LanguageProvider/__tests__/LanguageProvider.test.tsx
src/state/api/__tests__/apiSlice.test.ts
src/utils/sanity.tsx

Før:
```
Export "structureLocaleNamespace" of module "node_modules/sanity/lib/_chunks-es/pane.mjs" was reexported through module "node_modules/sanity/lib/structure.mjs" while both modules are dependencies of each other and will end up in different chunks by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "node_modules/sanity/lib/_chunks-es/pane.mjs" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.
Export "useDocumentPane" of module "node_modules/sanity/lib/_chunks-es/pane.mjs" was reexported through module "node_modules/sanity/lib/structure.mjs" while …
```

Flyttet sanityClient for å redusere byggstørrelsen

---

package-lock.json
package.json
vite.config.ts

[Trengs ikke lenger i v7](https://reactrouter.com/upgrading/v6#upgrade-to-v7:~:text=In%20v7%20we%20no%20longer%20need%20%22react%2Drouter%2Ddom%22%20as%20the%20packages%20have%20been%20simplified)

Fjernet ubrukt pakke react-router-dom

---

src/utils/__tests__/alder.test.ts

Denne testen: `src/utils/__tests__/alder.test.ts > alder-utils > isFoedselsdatoOverAlder > returnerer false når fødselsdatoen gir samme antall aar og måneder, og flere dager` feiler når dagens dato er mellom den 1. og 5. i måneden. Denne endringen bør fikse det.

Fiks test av isFoedselsdatoOverAlder

---

src/components/Simulering/utils-highcharts.ts
src/components/TabellVisning/TabellVisning.tsx

Skal vise null-verdier for AFP i tabell og graf

PEK-1047: Vis nullverdier for bare AFP i tabell og graf

---

cypress/e2e/pensjon/kalkulator/a11y.cy.ts
cypress/e2e/pensjon/kalkulator/avansert.cy.ts
cypress/e2e/pensjon/kalkulator/endring.cy.ts
src/translations/nb.ts

I avansert skjema, i felt for pensjonsgivende inntekt frem til pensjon/endring (øverst i skjemaet)
For brukere:
uten vedtak
med vedtak om UT
legg til "års" slik at det blir "Pensjonsgivende årsinntekt frem til pensjon" (i stedet for "Pensjonsgivende inntekt frem til pensjon").
For brukere:
med vedtak om AP
legg til "års" slik at det blir "Pensjonsgivende årsinntekt frem til endring" (i stedet for "Pensjonsgivende inntekt frem til endring").

Tesksjustering i Avansert skjema

---

src/context/LanguageProvider/LanguageProvider.tsx

Oppdaget feil i Sanity-integrasjonen der systemet logger feilmeldinger uavhengig av faktisk respons. Dette skjer fordi Sanity returnerer et array-objekt, noe som gjør at response.ok aldri blir `true`. Resultatet er at alle responser logges som feilende.
Dette er en unødvendig validering siden vi allerede har en catch-funksjon i samme promise-kjede som håndterer faktiske feil.

Fjern logging av feil fra Sanity ved !response.ok

---

.github/workflows/deploy.yaml

Dette gjør at vi kan rulle ut endringer til test-miljøer (sandbox, catbox, magicbox, dreambox, coffeebox, codebox) uten å vente på at testene er fullført. Dette gir raskere tilbakemelding på endringer i utviklingsmiljøene.
- Tester kjøres fortsatt, men blokkerer ikke utrulling til test-miljøer
- Utrulling til staging og produksjon krever fortsatt at alle tester passerer
Eksempel på bygg i `sandbox`: https://github.com/navikt/pensjonskalkulator-frontend/actions/runs/13993167435

PEK-1115: Optimaliser arbeidsflyt for test-miljøer ved å kjøre tester parallelt med utrulling

---

.github/dependabot.yml
package-lock.json
package.json

Fjerner @eslint/eslintrc:
https://www.npmjs.com/package/@eslint/eslintrc
> This package is not intended for use outside of the ESLint ecosystem.
Legger til `versioning-strategy: increase` i dependabot.yml i forsøk på å fikse et lite problem med at Dependabot ikke bumper alle pakker i gruppen "vitest" i package.json (eksempel: https://github.com/navikt/pensjonskalkulator-frontend/pull/1928/files). (Den bumper i lock-fila, så ikke noe stort problem.)

Fjern ubrukt pakke @eslint/eslintrc

---

package-lock.json
package.json

Brukes ikke direkte noe sted, så ser ikke noe poeng i å ha den i devDependencies.

Fjern @formatjs/ecma402-abstract fra dev-deps

---

src/components/AvansertSkjema/AvansertSkjemaForAndreBrukere/AvansertSkjemaForAndreBrukere.tsx
src/components/AvansertSkjema/AvansertSkjemaForBrukereMedGradertUfoeretrygd/AvansertSkjemaForBrukereMedGradertUfoeretrygd.tsx
src/components/AvansertSkjema/AvansertSkjemaForBrukereMedGradertUfoeretrygd/Beregningsvalg/Beregningsvalg.tsx
src/components/UtenlandsoppholdModal/UtenlandsoppholdModal.tsx
src/components/common/AgePicker/AgePicker.tsx
src/components/stegvisning/AFP/AFPOvergangskull/AFPOvergangskullUtenAP.tsx
src/components/stegvisning/AFP/AFPPrivat/AFPPrivat.tsx
src/components/stegvisning/AFP/AFPRadiogroup.tsx
src/components/stegvisning/SamtykkeOffentligAFP/SamtykkeOffentligAFP.tsx
src/components/stegvisning/SamtykkePensjonsavtaler/SamtykkePensjonsavtaler.tsx
src/components/stegvisning/Sivilstand/Sivilstand.tsx
src/components/stegvisning/Sivilstand/__tests__/Sivilstand.test.tsx
src/components/stegvisning/Utenlandsopphold/Utenlandsopphold.tsx

`aria-required` gjør at skjermleserbrukere får beskjed om at feltet er påkrevd. Fjerner det siden vi på startsiden skriver at du må "svare på alle spørsmålene". Siden alle felt er påkrevd uansett, gir det bare unødvendig støy for skjermleserbrukere. Dessuten er det inkonsekvent seende ikke får den samme informasjonen (ved hvert felt).
Fjerner i samme slengen `role=radiogroup` fordi det trolig bare ble satt for å kunne sette `aria-required`, og det er dårlig praksis å overstyre role unødvendig.

Fjern aria-required og role=radiogroup

---

cypress/e2e/pensjon/kalkulator/hovedhistorie.cy.ts
src/components/stegvisning/Start/StartForBrukereFyllt75.tsx
src/pages/StepStart/StepStart.tsx
src/utils/__tests__/alder.test.ts
src/utils/alder.ts

Del av oppgaven: [1184](https://jira.adeo.no/browse/PEK-1184) hvor ny aldersgrense ble avklart:
- Alders grense for å sjekke om brukeren skal få egen start side som sier at de ikke kan bruke kalkulatoren for å beregne Alders pensjon er endret fra 75 år til måneden bruker fyller 75 år + 1 måned
eks. bruker født 1. april og bruker født 30. april skal begge kom inn i kalkulatoren t.o.m. april. Fra 1.mai får de start side som informerer at de ikke kan bruke kalkulatoren

Check if user is 75 years plus 1 month to show the start page for 75

---

cypress/e2e/pensjon/kalkulator/med-samtykke-offentlig-tjenestepensjon.cy.ts
src/components/Pensjonsavtaler/OffentligTjenestePensjon/__tests__/OffentligTjenestepensjon.test.tsx
src/components/Pensjonsavtaler/OffentligTjenestePensjon/__tests__/utils.test.tsx
src/components/Pensjonsavtaler/OffentligTjenestePensjon/utils.ts

Grunnet feil TP-nummer for klp, må alle 4080 nummere endres til 4082

PEK-1262: Endret tp-nummer fra 4080 til 4082

---

src/components/AvansertSkjema/AvansertSkjemaForAndreBrukere/__tests__/AvansertSkjemaForAndreBrukere.test.tsx
src/components/stegvisning/__tests__/stegvisning-hooks.test.tsx
src/components/stegvisning/stegvisning-hooks.tsx
src/components/stegvisning/utils.ts
src/mocks/data/loepende-vedtak.json
src/mocks/mockedRTKQueryApiCalls.ts
src/pages/StepAFP/__tests__/StepAFP.test.tsx
src/pages/StepSamtykkeOffentligAFP/__tests__/StepSamtykkeOffentligAFP.test.tsx
src/pages/StepSamtykkePensjonsavtaler/__tests__/StepSamtykkePensjonsavtaler.test.tsx
src/pages/StepUfoeretrygdAFP/__tests__/StepUfoeretrygdAFP.test.tsx
src/pages/StepUtenlandsopphold/__tests__/StepUtenlandsopphold.test.tsx
src/router/__tests__/loaders.test.tsx
src/router/loaders.tsx
src/utils/__tests__/navigation.test.ts
src/utils/navigation.ts

Forbedrer navigasjonssystemet i stegvisning ved å implementere en ny metode for å bevare navigasjonsretningen i applikasjonen. Navigasjonsretningen lagres nå i URL-en ved hjelp av en query-parameter (`back=true`) som gjør det mulig å skille mellom framover- og bakovernavigering.
Introduserer en ny `skip`-funksjon som håndterer omdirigering basert på navigasjonsretningen og oppdaterer alle loader-funksjoner til å bruke denne. Testene er oppdatert for å verifisere korrekt navigasjonsadferd.

PEK-1084: Refaktorer navigering i stegvisning

---

.github/workflows/backup-sanity-dataset.yaml

Bruker Sanity "Viewer"-token opprettet i Sanity og Sanity GitHub Action.
Bruker Direct Workload Identity Federation (WIF) for GCP autentisering som er det tryggeste måten å autentisere GitHub mot GCP. Bruk av JSON-key koblet til service account er ikke anbefalt.
Aksel og Etterlatte gjorde noe lignende, men begge brukte javascript for å laste ned backups og JSON-key for autentisere mot GCP:
[https://github.com/navikt/aksel/blob/main/.github/workflows/backup-sanity.yml](https://github.com/navikt/aksel/blob/main/.github/workflows/backup-sanity.yml)
[https://github.com/navikt/pensjon-etterlatte/blob/main/.github/workflows/backup-brukerdialog-sanity-innhold.yaml](https://github.com/navikt/pensjon-etterlatte/blob/main/.github/workflows/backup-brukerdialog-sanity-innhold.yaml)

PEK-1219 backup sanity i gcp

---

src/components/Simulering/BeregningsdetaljerForOvergangskull/Felles/AlderspensjonDetaljer.tsx
src/components/Simulering/BeregningsdetaljerForOvergangskull/__tests__/hooks.test.ts
src/components/Simulering/BeregningsdetaljerForOvergangskull/hooks.ts

Lagt til no break spaces og unngått wrapping på HStack i detaljer. Dette gjør at verdien alltid er høyrestilt og ikke wrappes under teksten.

PEK-1373 Lister på smale skjermer

---

src/router/loaders.tsx

As part of this [PR](https://github.com/navikt/pensjonskalkulator-frontend/pull/2358/files#diff-00f47df6f7312d676f6c90b6182d06fdc364368008979f6664743a955fddd79bR100-R114) `getState` was moved before the api calls which leads to a problem where we do not log correct data to Umami/Amplitude.
In this PR, it is moved back to where it is supposed to be

Bugfix: Move getState after api calls are complete

---

src/translations/nb.ts

[PEK-1353](https://jira.adeo.no/browse/PEK-1353)
i modal som vises i Enkel og Avansert beregning:
> Før:
> <img width="468" height="370" alt="Screenshot 2025-10-06 at 10 50 53" src="https://github.com/user-attachments/assets/eddf597b-f51a-44a6-a2fc-ab7d9374eb7b" />
> 
> Etter:
> <img width="468" height="370" alt="Screenshot 2025-10-06 at 11 00 27" src="https://github.com/user-attachments/assets/6edc7e08-fe10-4d71-9e72-3a5f79324fec" />
> 
i Avansert skjema (øverst):
> Før:
> <img width="468" height="209" alt="Screenshot 2025-10-06 at 11 03 44" src="https://github.com/user-attachments/assets/bc903a24-1339-4b44-aac7-170b105f29cc" />
> 
> Etter:
> <img width="468" height="209" alt="Screenshot 2025-10-06 at 11 07 53" src="https://github.com/user-attachments/assets/77611ea6-db03-4848-8a0b-a6c4fc …

Justere tekst om PGI på beregningssiden for brukere med uføretrygd
